"""add index for fix unique register sesion per user

Revision ID: 1cf87908f488
Revises: 64d1cfeb4f4b
Create Date: 2026-05-12 00:53:17.411368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf87908f488'
down_revision = '64d1cfeb4f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_single_open_register'), postgresql_where="(status = 'open'::register_status)")
        batch_op.create_index('idx_single_open_register_per_user', ['opened_by', 'status'], unique=True, postgresql_where="(status = 'open'::register_status)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_single_open_register_per_user', postgresql_where="(status = 'open'::register_status)")
        batch_op.create_index(batch_op.f('idx_single_open_register'), ['status'], unique=True, postgresql_where="(status = 'open'::register_status)")

    # ### end Alembic commands ###
