"""MVP Schema Limpio

Revision ID: 7be5b50510c2
Revises: 
Create Date: 2026-05-07 23:22:19.424824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be5b50510c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='generic_status'), server_default=sa.text("'active'::generic_status"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    sa.UniqueConstraint('slug', name='categories_slug_key')
    )
    op.create_table('store_settings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('commercial_name', sa.String(length=150), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=150), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default=sa.text("'COP'::character varying"), nullable=True),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'es-CO'::character varying"), nullable=True),
    sa.Column('timezone', sa.String(length=60), server_default=sa.text("'America/Bogota'::character varying"), nullable=True),
    sa.Column('country_code', sa.String(length=5), server_default=sa.text("'CO'::character varying"), nullable=True),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), server_default=sa.text('19.00'), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=20), server_default=sa.text("'FAC'::character varying"), nullable=True),
    sa.Column('next_invoice_number', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('receipt_footer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='store_settings_pkey')
    )
    op.create_table('tables',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default=sa.text('2'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='generic_status'), server_default=sa.text("'active'::generic_status"), nullable=True),
    sa.PrimaryKeyConstraint('id', name='tables_pkey'),
    sa.UniqueConstraint('name', name='tables_name_key')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'cashier', 'barista', name='user_role'), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'terminated', name='user_status'), server_default=sa.text("'active'::user_status"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('sku', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('stock', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('min_stock', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='generic_status'), server_default=sa.text("'active'::generic_status"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('price >= 0::numeric', name='products_price_check'),
    sa.CheckConstraint('unit_cost >= 0::numeric', name='products_unit_cost_check'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('sku', name='products_sku_key')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_products_name', ['name'], unique=False)
        batch_op.create_index('idx_products_status', ['status'], unique=False)

    op.create_table('register_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('opening_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('opened_by', sa.Uuid(), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closing_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='register_status'), server_default=sa.text("'open'::register_status"), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', name='register_sessions_pkey')
    )
    with op.batch_alter_table('register_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_single_open_register', ['status'], unique=True, postgresql_where="(status = 'open'::register_status)")

    op.create_table('orders',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('register_session_id', sa.Uuid(), nullable=True),
    sa.Column('table_id', sa.Uuid(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'preparing', 'ready', 'paid', 'cancelled', name='order_status'), server_default=sa.text("'open'::order_status"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('idx_orders_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_orders_status', ['status'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('historical_cost', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='order_items_quantity_check'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id', name='order_items_pkey')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('method', sa.Enum('cash', 'card', 'transfer', name='payment_method'), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('register_session_id', sa.Uuid(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('amount_paid > 0::numeric', name='payments_amount_paid_check'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('idx_payments_order_id', ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('idx_payments_order_id')

    op.drop_table('payments')
    op.drop_table('order_items')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('idx_orders_status')
        batch_op.drop_index('idx_orders_created_at')

    op.drop_table('orders')
    with op.batch_alter_table('register_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_single_open_register', postgresql_where="(status = 'open'::register_status)")

    op.drop_table('register_sessions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('idx_products_status')
        batch_op.drop_index('idx_products_name')

    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('tables')
    op.drop_table('store_settings')
    op.drop_table('categories')
    # ### end Alembic commands ###
