"""add cash_movements table for audit

Revision ID: f1d49fa84e80
Revises: 6ba18217ab3f
Create Date: 2026-05-08 13:37:27.937387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1d49fa84e80'
down_revision = '6ba18217ab3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('movement_type', sa.Enum('opening', 'closing', 'withdrawal', 'deposit', 'adjustment', name='movement_type'), nullable=False))
        batch_op.add_column(sa.Column('reference_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reference_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('balance_before', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.alter_column('register_session_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.create_index('idx_cash_movements_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_cash_movements_session', ['register_session_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('reason')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('income', 'expense', name='movement_type'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_cash_movements_session')
        batch_op.drop_index('idx_cash_movements_created_at')
        batch_op.alter_column('register_session_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('balance_after')
        batch_op.drop_column('balance_before')
        batch_op.drop_column('description')
        batch_op.drop_column('reference_id')
        batch_op.drop_column('reference_type')
        batch_op.drop_column('movement_type')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
